const quotes = [
    "The only limit to our realization of tomorrow is our doubts of today.",  
    "Success is not the key to happiness. Happiness is the key to success.",  
    "In the middle of difficulty lies opportunity.",  
    "The best way to predict the future is to create it.",  
    "Life is what happens when you're busy making other plans.",  
    "Courage is grace under pressure.",  
    "Do not watch the clock. Do what it does. Keep going.",  
    "The secret of getting ahead is getting started.",  
    "Believe you can and you're halfway there.",  
    "The best time to plant a tree was 20 years ago. The second best time is now.",  
    "The only way to do great work is to love what you do.",  
    "Life is either a daring adventure or nothing at all.",  
    "You miss 100% of the shots you don’t take.",  
    "The journey of a thousand miles begins with one step.",  
    "Strive not to be a success, but rather to be of value.",  
    "What lies behind us and what lies before us are tiny matters compared to what lies within us.",  
    "It does not matter how slowly you go as long as you do not stop.",  
    "Perseverance is not a long race; it is many short races one after the other.",  
    "Happiness is not something ready made. It comes from your own actions.",  
    "If you can dream it, you can achieve it.",  
    "The harder you work for something, the greater you’ll feel when you achieve it.",  
    "Don’t wait. The time will never be just right.",  
    "Change your thoughts and you change your world.",  
    "The mind is everything. What you think, you become.",  
    "It’s not about how hard you hit. It’s about how hard you can get hit and keep moving forward.",  
    "The future belongs to those who believe in the beauty of their dreams.",  
    "Don’t count the days, make the days count.",  
    "Your time is limited, don’t waste it living someone else’s life.",  
    "You can’t use up creativity. The more you use, the more you have.",  
    "Success is not in what you have, but who you are.",  
    "The best revenge is massive success.",  
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart.",  
    "If you want to lift yourself up, lift up someone else.",  
    "If you want to achieve greatness stop asking for permission.",  
    "I am not a product of my circumstances. I am a product of my decisions.",  
    "Challenges are what make life interesting and overcoming them is what makes life meaningful.",  
    "The only person you are destined to become is the person you decide to be.",  
    "Don’t be afraid to give up the good to go for the great.",  
    "You have within you right now, everything you need to deal with whatever the world can throw at you.",  
    "The man who moves a mountain begins by carrying away small stones.",  
    "You are never too old to set another goal or to dream a new dream.",  
    "You can’t fall if you don’t climb. But there’s no joy in living your whole life on the ground.",  
    "It’s not the years in your life that count. It’s the life in your years.",  
    "Dream big and dare to fail.",  
    "Life isn’t about finding yourself. Life is about creating yourself.",  
    "The only impossible journey is the one you never begin.",  
    "Success usually comes to those who are too busy to be looking for it.",  
    "The biggest risk is not taking any risk.",  
    "Do what you can, with what you have, where you are.",  
    "Start where you are. Use what you have. Do what you can.",  
    "You have to be at your strongest when you’re feeling at your weakest.",  
    "Nothing will work unless you do.",  
    "The harder the conflict, the greater the triumph.",  
    "Go confidently in the direction of your dreams. Live the life you have imagined.",  
    "You are the artist of your own life. Don’t hand the paintbrush to anyone else.",  
    "It’s never too late to be what you might have been.",  
    "The only thing standing between you and your goal is the story you keep telling yourself as to why you can’t achieve it.",  
    "Success is not how high you have climbed, but how you make a positive difference to the world.",  
    "The road to success and the road to failure are almost exactly the same.",  
    "Happiness is not something you postpone for the future; it is something you design for the present.",  
    "If you don’t build your dream, someone else will hire you to help them build theirs.",  
    "The more you praise and celebrate your life, the more there is in life to celebrate.",  
    "I never dreamed about success, I worked for it.",  
    "Success is how high you bounce when you hit bottom.",  
    "Be not afraid of life. Believe that life is worth living, and your belief will help create the fact.",  
    "What you get by achieving your goals is not as important as what you become by achieving your goals.",  
    "Action is the foundational key to all success.",  
    "Believe in yourself and all that you are. Know that there is something inside you that is greater than any obstacle.",  
    "Dreams don’t work unless you do.",  
    "If you want to fly, give up everything that weighs you down.",  
    "We may encounter many defeats but we must not be defeated.",  
    "Success is the sum of small efforts, repeated day in and day out.",  
    "The only limit to your impact is your imagination and commitment.",  
    "Don’t let yesterday take up too much of today.",  
    "What seems to us as bitter trials are often blessings in disguise.",  
    "It always seems impossible until it’s done.",  
    "Don’t be discouraged. It’s often the last key in the bunch that opens the lock.",  
    "The purpose of life is not to be happy. It is to be useful, to be honorable, to be compassionate, to have it make some difference that you have lived and lived well.",  
    "No matter how hard the past, you can always begin again.",  
    "A goal is not always meant to be reached; it often serves simply as something to aim at.",  
    "You can’t go back and change the beginning, but you can start where you are and change the ending.",  
    "The only way to achieve the impossible is to believe it is possible.",  
    "If opportunity doesn’t knock, build a door.",  
    "It’s not what we have in life, but who we have in our life that matters.",  
    "Every strike brings me closer to the next home run.",  
    "When you have a dream, you’ve got to grab it and never let go.",  
    "You must be the change you wish to see in the world.",  
    "Every great dream begins with a dreamer.",  
    "If you don’t like something, change it. If you can’t change it, change your attitude.",  
    "Every accomplishment starts with the decision to try.",  
    "Don’t let what you cannot do interfere with what you can do.",  
    "You can, you should, and if you’re brave enough to start, you will.",  
    "The past cannot be changed. The future is yet in your power.",  
    "The expert in anything was once a beginner.",  
    "You must do the things you think you cannot do.",  
    "Great things never come from comfort zones.",  
    "If you are not willing to risk the usual, you will have to settle for the ordinary.",  
    "The best way out is always through.",  
    "Don’t let anyone dull your sparkle."
];

const usedIndexes = new Set()
const quoteElement = document.getElementById("quote")

function generateQuote (){
    if (usedIndexes.size >= quotes.length) {
        usedIndexes.clear();
    }

    let randomIdx;
    do {
        randomIdx = Math.floor(Math.random() * quotes.length);
    } while (usedIndexes.has(randomIdx)); // Ensure the index hasn't been used

    const quote = quotes[randomIdx];
    quoteElement.innerHTML = quote; // Display the quote
    usedIndexes.add(randomIdx); // Mark this index as used
}
